---
- name: Generate security content
  ansible.builtin.include_role:
    name: "module_openapi_security"
  when: ( plugin['content'] is not defined ) or ( plugin['content'] == 'security' )

- name: Generate cloud content
  ansible.builtin.include_role:
    name: "module_openapi_cloud"
  when: plugin['content'] == 'cloud'
